about_me/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from about_me import views

urlpatterns = [
    url(r'^about_me/$', views.about_me, name='about_me'),
]

gallery/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from gallery import views

urlpatterns = [
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^gallery/lovestory/$', views.lovestory, name='lovestory'),
    url(r'^gallery/individual/$', views.individual, name='individual'),
    url(r'^gallery/family/$', views.family, name='family'),
    # url(r'^gallery/(?P<gallery_category>\w+)/$', views.galleries, name='galleries'),
    url(r'^gallery/(?P<gallery_id>\w+)/$', views.galleries, name='galleries'),

]

landing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from landing import views

urlpatterns = [


    url(r'^$', views.landing, name='landing'),
    url(r'^$', views.landing, name='landing'),

]

my_contact/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from my_contact import views

urlpatterns = [
    url(r'^my_contact/$', views.my_contact, name='my_contact'),

]

proksyphoto/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^', include('gallery.urls')),
    url(r'^', include('about_me.urls')),
    url(r'^', include('my_contact.urls')),
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models


class GalleryCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категорія галереї'
        verbose_name_plural = 'Категорія галерей'


class Gallery(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(GalleryCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    short_description = models.TextField(blank=True, null=True, default=None)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Галлерея'
        verbose_name_plural = 'Галлереї'


class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='gallery_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотографія'
        verbose_name_plural = 'Фотографії'

landing/models.py
from django.db import models


class Subscriber(models.Model):

    call_number = models.CharField("Номер телефону",max_length=128)
    name = models.CharField("Ім'я", max_length=128)
    message = models.CharField('Повідомлення', max_length=128)
    event_date =models.CharField('Час та дата фотосесії', max_length=128)

    def __str__(self):
        return "Пользователь %s %s" % (self.name, self.call_number,)

    class Meta:
        verbose_name = 'Запит'
        verbose_name_plural = 'Запити на фотосесію'

my_contact/models.py
from django.db import models

gallery/forms.py
from django import forms
from .models import *

# class SubscriberForm(forms.ModelForm):
#
# 	class Meta:
# 		model = Subscriber
# 		exclude = [""]

landing/forms.py
from django import forms
from .models import *


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        exclude = [""]

my_contact/forms.py
from django import forms
from .models import *

about_me/views.py
from django.shortcuts import render
# from .forms import SubscriberForm
from about_me.models import *

def about_me(request):
	# gallery_images = GalleryImage.objects.filter(is_active = True, is_main=True)
	return render(request, 'about_me/about_me.html', locals())

gallery/views.py
from django.shortcuts import render
from gallery.models import *

def gallery(request):
    gallery_images = GalleryImage.objects.filter(is_active=True, is_main=True)
    return render(request, 'galleries/gallery.html',  locals())




def galleries(request, gallery_id):
    gallery_images = GalleryImage.objects.filter(is_active=True, is_main=True)
    gallery = Gallery.objects.get(id=gallery_id)
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    print(request.session.session_key)

    return render(request, 'galleries/photossession.html', locals())

def lovestory(request):

    gallery_images = GalleryImage.objects.filter(is_active=True, is_main=True)
    gallery_images_lovestory = gallery_images.filter(gallery__category__id=2)
    return  render(request, 'galleries/lovestory.html', locals())

def individual(request):

    gallery_images = GalleryImage.objects.filter(is_active=True, is_main=True)
    gallery_images_lovestory = gallery_images.filter(gallery__category__id=3)
    return  render(request, 'galleries/lovestory.html', locals())

def family(request):

    gallery_images = GalleryImage.objects.filter(is_active=True, is_main=True)
    gallery_images_lovestory = gallery_images.filter(gallery__category__id=4)
    return  render(request, 'galleries/lovestory.html', locals())

landing/views.py
from django.shortcuts import render
from .forms import SubscriberForm




def landing(request):
    form = SubscriberForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        print(request.POST)
        print(form.cleaned_data)
        data = form.cleaned_data

        print (data['name'])

        form = form.save()

    return render(request, 'landing/landing.html', locals())

my_contact/views.py
from django.shortcuts import render
# from .forms import SubscriberForm
from my_contact.models import *

def my_contact(request):
	return render(request, 'my_contact/my_contact.html', locals())

templates/about_me/about_me.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section section-md bg-white">
        <div class="shell">
          <div class="range range-50 range-sm-center range-md-left">
            <div class="cell-sm-6 cell-md-5">
              <div class="thumb-bordered"><img src="{% static 'images/about_me.jpg' %}" alt="" width="437" height="435">
              </div>
            </div>
            <div class="cell-sm-6 cell-md-7">
              <div class="box-width-3 box-centered">
                <article class="quote-big">
                  <p class="q">Привіт! Мене звати Ксю, або ж просто Оксана).</p>
                </article>
                <div class="divider"></div>
                <p class="text-spacing-05">Трохи про мене
                    ФОТОГРАФ
                    Оксана Бобровська
                    Привіт! Дякую,що ви зараз тут ,на моєму сайті !.Найбільше про мене можуть сказати фото ,але якщо в двох словах ,то ось що вам потрібно знати .
                    Я щира,сонячна та проста в спілкуванні  людина і з таким посилом та настроєм стараюсь  йти до вас на фотозйомку. Про що я фотографую ?
                    Фотографую про людей .Найбільше люблю історії наповненні щирістю і любов'ю ,а саме сімейна фотосесія та lovestory.
                    В індивідуальній зйомці намагаюсь передати особливість людини  та висловити концепцію,задуманий образ через фото.
                    Отож ,продумана композиція ,підготовлений образ і непідробні емоції - забезпечують створити хороші кадри. А це я вам гарантую ;)
                    І пам'ятайте кожен момент в житті важливий .</p>
                  <p class="text-spacing-05">
                      Контакти
                        Instagram
                        Я завжди відкрита до нових пропозицій та несподіваних подорожей . Якщо у вас є ідеї зйомок ,пишіть ! Буду дуже рада втілити вашу фотоідею.<br>
                        E-mail :  oksanabobrovska97@gmail.com<br>
                        Телефон : +380966610798.<br>
                        Працюю в м .Рівне ,м.Київ та Львів. У всіх одночасно не можу бути ,тому бронюйте свою дату заздалегідь.
                        Вартують мої послуги - 600 грн./1 год.
                  </p>
                  <p class="text-spacing-05">

                    Портфоліо :<br>
                    Індивідуальна зйомка<br>
                    Сімейна фотосесія<br>
                    Lovestory</p>
                <div class="group-3-columns" data-lightgallery="group">
                  <div class="column-item"><a class="thumb-light" href="{% static 'images/family.jpg' %}" data-lightgallery="item"><img src="{% static 'images/family.jpg' %}" alt="" width="120" height="171">
                      <div class="thumb-light__overlay"></div></a></div>
                  <div class="column-item"><a class="thumb-light" href="{% static 'images/ind.jpg' %}" data-lightgallery="item"><img src="{% static 'images/ind.jpg' %}" alt="" width="120" height="171">
                      <div class="thumb-light__overlay"></div></a></div>
                  <div class="column-item"><a class="thumb-light" href="{% static 'images/lovestory.jpg' %}" data-lightgallery="item"><img src="{% static 'images/lovestory.jpg' %}" alt="" width="120" height="171">
                      <div class="thumb-light__overlay"></div></a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">
  <head>
    <!-- Site Title-->
    <title>Home</title>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'images/favicon.css' %}">

    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:300,400,700,400italic%7CJosefin+Sans:400,700,300italic">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!--[if lt IE 10]>
    <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="images/ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <script src="js/html5shiv.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div id="page-loader">
      <div class="page-loader-body">
        <div class="cssload-spinner">
          <div class="cssload-cube cssload-cube0"></div>
          <div class="cssload-cube cssload-cube1"></div>
          <div class="cssload-cube cssload-cube2"></div>
          <div class="cssload-cube cssload-cube3"></div>
          <div class="cssload-cube cssload-cube4"></div>
          <div class="cssload-cube cssload-cube5"></div>
          <div class="cssload-cube cssload-cube6"></div>
          <div class="cssload-cube cssload-cube7"></div>
          <div class="cssload-cube cssload-cube8"></div>
          <div class="cssload-cube cssload-cube9"></div>
          <div class="cssload-cube cssload-cube10"></div>
          <div class="cssload-cube cssload-cube11"></div>
          <div class="cssload-cube cssload-cube12"></div>
          <div class="cssload-cube cssload-cube13"></div>
          <div class="cssload-cube cssload-cube14"></div>
          <div class="cssload-cube cssload-cube15"></div>
        </div>
      </div>
    </div>
    <!-- Page-->
    <div class="page">
      <!-- Page header-->
      <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-lg-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="5px" data-lg-stick-up-offset="5px" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="{% url 'landing'%}">
                      <div class="brand__name"><img class="brand__logo-dark" src="{% static 'images/logo.png'%}" alt="" width="243" height="57"/><img class="brand__logo-light" src="{% static 'images/logo.png'%}" alt="" width="243" height="57"/>
                      </div></a></div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap">
                  <div class="rd-navbar-element">
                    <ul class="list-icons list-inline-sm">
                      <li><a target="_blank" class="icon icon-sm fa fa-instagram icon-style-camera" href="https://www.instagram.com/proksyphoto/"><span></span><span></span><span></span><span></span></a></li>
                      <li><a target="_blank" class="icon icon-sm fa fa-facebook icon-style-camera" href="https://www.facebook.com/profile.php?id=100011105650016"><span></span><span></span><span></span><span></span></a></li>
{#                      <li><a class="icon icon-sm fa fa-pinterest icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>#}
                    </ul>
                  </div>
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li class="active"><a href="{% url 'landing' %}">Home</a>
                    </li>
                    <li><a href="{% url 'about_me' %}">Про мене</a>
                    </li>
                    <li>
                         <a class="btn btn-link" data-toggle="collapse" data-target="#demo">Портфоліо</a>
                            <div id="demo" class="collapse">
                                <ul class="list-inline-lg">
                                    <li><a  class="dropdown-item" href="{% url 'gallery' %}">Всі</a></li>
                                    <li><a class="dropdown-item" href="{% url 'lovestory' %}">lovestory</a></li>
                                    <li><a class="dropdown-item" href="{% url 'individual' %}">Індивідуальна</a></li>
                                    <li><a class="dropdown-item" href="{% url 'family' %}">Сімейна</a></li>
                                </ul>
                            </div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
        {% block content %}
        {% endblock content %}


    </div>



      <footer class="footer-centered section bg-gray-darker">
        <div class="shell">
          <div class="range range-sm-center">
            <div class="cell-sm-10 cell-md-8 cell-lg-6">

              <ul class="list-icons list-inline-sm">
                <li><a target="_blank" class="icon icon-sm fa fa-instagram icon-style-camera" href="https://www.instagram.com/proksyphoto/"><span></span><span></span><span></span><span></span></a></li>
                <li><a target="_blank" class="icon icon-sm fa fa-facebook icon-style-camera" href="https://www.facebook.com/profile.php?id=100011105650016"><span></span><span></span><span></span><span></span></a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->
    <script src="{% static 'js/core.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>


    <!-- fancyBox CSS -->
    <link rel="stylesheet" href="{% static 'fancybox/dist/jquery.fancybox.min.css' %}">

    <!-- fancyBox JS -->
    <script src="{% static 'fancybox/dist/jquery.fancybox.min.js' %}"></script>
    <!-- coded by starlight-->

  </body>
</html>

templates/galleries/family.html
{% extends 'base.html' %}
{% block content %}
{#<div class="rd-navbar-wrap">#}
{#    <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-lg-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="5px" data-lg-stick-up-offset="5px" data-md-stick-up="true" data-lg-stick-up="true">#}
{#        <div class="rd-navbar-main-outer">#}
{#            <ul class="rd-navbar-nav">#}
{#                <li class="active"><a href="{% url 'gallery' %}">Всі</a>#}
{#                </li>#}
{#                <li class=""><a href="{% url 'lovestory' %}">lovestory</a>#}
{#                </li>#}
{#                <li><a href="{% url 'individual' %}">Індивідуальна</a>#}
{#                </li>#}
{#                <li><a href="{% url 'family' %}">Сімейна</a>#}
{#                </li>#}
{#            </ul>#}
{#        </div>#}
{#    </nav>#}
{#</div>#}
<div class="section section1">
    <div class="container">
        <div class="row">
            {% for gallery_image in gallery_images_family %}
                {% include 'galleries/gallery_item.html' %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/galleries/gallery.html
{% extends 'base.html' %}

{% block content %}


{#        <div class="rd-navbar-wrap">#}
{#            <nav class="rd-navbar" >#}
{#                <div class="rd-navbar-main-outer">#}
{#                    <ul class="rd-navbar-nav">#}
{#                        <li class="active"><a href="{% url 'gallery' %}">Всі</a>#}
{#                        </li>#}
{#                        <li class=""><a href="{% url 'lovestory' %}">lovestory</a>#}
{#                        </li>#}
{#                        <li><a href="{% url 'individual' %}">Індивідуальна</a>#}
{#                        </li>#}
{#                        <li><a href="{% url 'family' %}">Сімейна</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#            </nav>#}
{#        </div>#}

        <div class="section section1">
            <div class="container">
                <div class="row">
                    {% for gallery_image in gallery_images %}
                        {% include 'galleries/gallery_item.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>



{% endblock %}

templates/galleries/gallery_item.html
<div class="col-lg-3">
    <div class="product-item">
        <a href="{% url 'galleries' gallery_image.gallery.id %}">
            <img src="{{ gallery_image.image.url }}" alt="">
        </a>
        <div>
            <h4>{{ gallery_image.gallery.name }}</h4>
            <p>
            {{gallery_image.gallery.description|truncatechars_html:20}}
            </p>
        </div>
    </div>
</div>

templates/galleries/individual.html
{% extends 'base.html' %}
{% block content %}
{#<div class="rd-navbar-wrap">#}
{#    <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-lg-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="5px" data-lg-stick-up-offset="5px" data-md-stick-up="true" data-lg-stick-up="true">#}
{#        <div class="rd-navbar-main-outer">#}
{#            <ul class="rd-navbar-nav">#}
{#                <li class="active"><a href="{% url 'gallery' %}">Всі</a>#}
{#                </li>#}
{#                <li class=""><a href="{% url 'lovestory' %}">lovestory</a>#}
{#                </li>#}
{#                <li><a href="{% url 'individual' %}">Індивідуальна</a>#}
{#                </li>#}
{#                <li><a href="{% url 'family' %}">Сімейна</a>#}
{#                </li>#}
{#            </ul>#}
{#        </div>#}
{#    </nav>#}
{#</div>#}
<div class="section section1">
    <div class="container">
        <div class="row">
            {% for gallery_image in gallery_images_individual %}
                {% include 'galleries/gallery_item.html' %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/galleries/lovestory.html
{% extends 'base.html' %}
{% block content %}
{#<div class="rd-navbar-wrap">#}
{#    <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-lg-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="5px" data-lg-stick-up-offset="5px" data-md-stick-up="true" data-lg-stick-up="true">#}
{#        <div class="rd-navbar-main-outer">#}
{#            <ul class="rd-navbar-nav">#}
{#                <li class="active"><a href="{% url 'gallery' %}">Всі</a>#}
{#                </li>#}
{#                <li class=""><a href="{% url 'lovestory' %}">lovestory</a>#}
{#                </li>#}
{#                <li><a href="{% url 'individual' %}">Індивідуальна</a>#}
{#                </li>#}
{#                <li><a href="{% url 'family' %}">Сімейна</a>#}
{#                </li>#}
{#            </ul>#}
{#        </div>#}
{#    </nav>#}
{#</div>#}
<div class="section section1">
    <div class="container">
        <div class="row">
            {% for gallery_image in gallery_images_lovestory %}
                {% include 'galleries/gallery_item.html' %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/galleries/photossession.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="row">

            {% for image_item in gallery.galleryimage_set.all %}
                <div class="col-lg-3 col-md-4 col-6 thumb">
                    <div class="product-item">
                        <a data-fancybox="gallery" href="{{ image_item.image.url }}" >
                            <img class="img-fluid" src="{{ image_item.image.url }}" alt="">
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/landing/contact_form.html
      <!-- Book Your Photo Shoot-->
      <section class="section section-md bg-white">
        <div class="shell">
          <div class="range range-50 range-sm-center range-md-left range-md-reverse range-md-middle">
            <div class="cell-sm-10 cell-md-6 wow fadeInRight">
              <div class="box-width-4 box-centered">
                <p class="heading-1">Забронюйте <br> Вашу подію</p>
                <p>Щоб замовити фотосесію, будь ласка, внесіть якомога більше деталей щодо вашої конкретної події. Я уточню умови відразу після отримання вашого повідомлення!</p>
              </div>
            </div>
            <div>
             <div class="cell-sm-10 cell-md-6 wow fadeInLeft">
                  <article class="box-line"><span></span><span></span><span></span><span></span>
                    <div class="box-line__main">
                      <form class="rd-mailform" data-form-output="form-output-global" data-form-type="contact" method="POST">{% csrf_token %}
                          <div class="form-group">
                          <input class="form-input" id="contact-date" type="text" data-time-picker="date" name="{{ form.event_date.name }}" data-constraints="@Required">
                          <label class="form-label" for="contact-date">Дата події</label>
                        </div>

                        <div class="form-wrap">
                          <input class="form-input" id="contact-name" type="text" name="{{ form.name.name}}" data-constraints="@Required">
                          <label class="form-label" for="contact-name">Ваше ім'я</label>
                        </div>
                        <div class="form-wrap">
                            <label class="form-label" for="phone">Номер телефону</label>
                          <input class="form-input"  id="phone" name="{{ form.call_number.name}}" data-constraints="@Required">

                        </div>

                        <div class="form-wrap">
                          <label class="form-label" for="contact-message">Ваше повідомлення</label>
                          <textarea class="form-input" id="contact-message" name="{{ form.message.name}}" data-constraints="@Required"></textarea>
                        </div>


                        <div class="form-wrap form-button offset-1">
                          <button class="button button-block button-primary-outline button-ujarak" type="submit">замовити</button>
                        </div>
                      </form>
                    </div>
                  </article>
             </div>
            </div>
          </div>
        </div>
      </section>

templates/my_contact/my_contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
          <!-- Get in Touch-->
      {% include 'landing/contact_form.html' %}
{% endblock %}

templates/navbar.html
<div id="page-loader">
      <div class="page-loader-body">
        <div class="cssload-spinner">
          <div class="cssload-cube cssload-cube0"></div>
          <div class="cssload-cube cssload-cube1"></div>
          <div class="cssload-cube cssload-cube2"></div>
          <div class="cssload-cube cssload-cube3"></div>
          <div class="cssload-cube cssload-cube4"></div>
          <div class="cssload-cube cssload-cube5"></div>
          <div class="cssload-cube cssload-cube6"></div>
          <div class="cssload-cube cssload-cube7"></div>
          <div class="cssload-cube cssload-cube8"></div>
          <div class="cssload-cube cssload-cube9"></div>
          <div class="cssload-cube cssload-cube10"></div>
          <div class="cssload-cube cssload-cube11"></div>
          <div class="cssload-cube cssload-cube12"></div>
          <div class="cssload-cube cssload-cube13"></div>
          <div class="cssload-cube cssload-cube14"></div>
          <div class="cssload-cube cssload-cube15"></div>
        </div>
      </div>
    </div>
    <!-- Page-->
    <div class="page">
      <!-- Page header-->
      <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-lg-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="5px" data-lg-stick-up-offset="5px" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="/">
                      <div class="brand__name"><img class="brand__logo-dark" src="{% static 'images/logo-243x57.png'%}" alt="" width="243" height="57"/><img class="brand__logo-light" src="{% static 'images/logo-inverse-243x57.png'%}" alt="" width="243" height="57"/>
                      </div></a></div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap">
                  <div class="rd-navbar-element">
                    <ul class="list-icons list-inline-sm">
                      <li><a class="icon icon-sm fa fa-instagram icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
                      <li><a class="icon icon-sm fa fa-facebook icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
                      <li><a class="icon icon-sm fa fa-pinterest icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>
                    </ul>
                  </div>
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li class="active"><a href="index.html">Home</a>
                    </li>
                    <li><a href="about-me.html">Про мене</a>
                    </li>
                    <li><a href="typography.html">Портфолiо</a>
                    </li>
                    <li><a href="contact-me.html">Мої контакти</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>